#!/usr/local/bin/lua

str    = require "org.conman.string"
syslog = require "org.conman.syslog"
net    = require "org.conman.net"
fsys   = require "org.conman.fsys"
unix   = require "org.conman.unix"
errno  = require "org.conman.errno"
proc   = require "org.conman.process"
sig    = require "org.conman.process".sig
         require "readacl"

dofile("/home/spc/source/daemon/acl/version.lua")
syslog.open('ipacld','daemon')
syslog('notice',"ipacld " .. VERSION .. " starting up")

if arg[1] == nil then
  dofile("ipacl.conf")
else
  dofile(arg[1])
end

local g_sock
local g_acl = {}

-- *********************************************************************

function log_success(remote,cred,addr,stype)
  syslog('notice',string.format("success: rem=%s uid=%s gid=%s family=%s addr=%s port=%s type=%s",
  		tostring(remote),
      		cred.uid,
      		cred.gid,
      		addr.family,
      		addr.addr,
      		addr.port,
      		stype))      		
end

-- *********************************************************************

function log_failure(remote,cred,addr,stype,err)
  syslog('err',string.format("failure: err=%q rem=%s uid=%s gid=%s family=%s addr=%s port=%s type=%s",
  		errno.strerror(err),
  		tostring(remote),
      		cred.uid,
      		cred.gid,
      		addr.family,
      		addr.addr,
      		addr.port,
      		stype))
end

-- *********************************************************************

function main()
  local remote
  local data
  local cred
  local err
  local addr
  local stype
  local sock
  local key
  local _
  
  remote,data,cred,err = readcred(g_sock)
  if err ~= 0 then
    if err == errno.EINTR then
      g_sock:close()
      os.remove("/dev/ipacl")
      os.exit(1)
    end
    syslog('crit',string.format("readcred() = %s",errno.strerror(err)))
    return main()
  end
  
  if unix.users[cred.uid] ~= nil then
    cred.uid = unix.users[cred.uid].userid
  else
    syslog('warn',string.format("user %d does not exist",cred.uid))
    senderr(g_sock,remote,errno.EPERM)
    return main()
  end
  
  if unix.groups[cred.gid] ~= nil then
    cred.gid = unix.groups[cred.gid].name
  else
    syslog('warn',string.format("group %d does not exist",cred.gid))
    senderr(g_sock,remote,errno.EPERM)
  end
  
  addr,stype,err = acl_decode(data)
  if err ~= 0 then
    log_failure(remote,cred,addr,stype,err)
    senderr(g_sock,remote,err)
    return main()
  end

  -- ------------------------------
  -- get the TCP, UDP or RAW table
  -- ------------------------------

  val = g_acl[stype]
  if val == nil then
    log_failure(remote,cred,addr,stype,errno.EINVAL)
    senderr(g_sock,remote,errno.EINVAL)
    return main()
  end

  -- ----------------------
  -- get the address table
  -- ----------------------

  key = string.format("%s:%s",addr.addr,addr.port)  
  val = val[key]
  if val == nil then
    log_failure(remote,cred,addr,stype,errno.EPERM)
    senderr(g_sock,remote,errno.EPERM)
    return main()
  end
  
  -- -----------------------------------
  -- get if the user can open this port
  -- -----------------------------------

  val = val[cred.uid]
  if val == nil then
    log_failure(remote,cred,addr,stype,errno.EPERM)
    senderr(g_sock,remote,errno.EPERM)
    return main()
  end
  
  -- -------------------------------------------------------------------
  -- if this is a function, run it, passing the group value.  This had
  -- better return a bool
  -- -------------------------------------------------------------------

  if type(val) == 'function' then 
    val = val(cred.gid) 
  end
  
  if not val then
    log_failure(remore,cred,addr,stype,errno.EPERM)
    senderr(g_sock,remote,errno.EPERM)
    return main()
  end

  -- ------------------------------------------
  -- create the requested socket and return it
  -- ------------------------------------------

  sock,err = net.socket(addr.family,stype)
  if err ~= 0 then
    log_failure(remote,cred,addr,stype,err)
    senderr(g_sock,remote,err)
    return main()
  end
  
  err = sock:bind(addr)
  if err ~= 0 then
    log_failure(remote,cred,addr,stype,err)
    senderr(g_sock,remote,err)
    sock:close()
    return main()
  end

  log_success(remote,cred,addr,stype)  
  sendfd(g_sock,remote,sock:fd())
  sock:close()
  return main()
end

-- *************************************************************************  

g_acl = 
{
  tcp = TCP,
  udp = UDP,
  raw = RAW
}

sig.catch(sig.INT)
fsys.umask("--x--x--x")
os.remove("/dev/ipacl")
laddr = net.address("/dev/ipacl")
g_sock  = net.socket(laddr.family,'udp')
g_sock:bind(laddr)
recvcred(g_sock)

main()
