#!/usr/local/bin/lua
-- ***************************************************************
--
-- Copyright 2012 by Sean Conner.  All Rights Reserved.
--
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License
-- along with this program.  If not, see <http://www.gnu.org/licenses/>.
--
-- Comments, questions and criticisms can be sent to: sean@conman.org
--
-- ********************************************************************

syslog  = require "org.conman.syslog"
net     = require "org.conman.net"
errno   = require "org.conman.errno"
proc    = require "org.conman.process"
sig     = require "org.conman.process".sig
ipacl_s = require "org.conman.net.ipacl_s"

-- *********************************************************************

function log_success(remote,cred,addr,proto)
  syslog('notice',"success: rem=%s uid=%s gid=%s family=%s addr=%s proto=%s port=%s",
  		tostring(remote),
      		cred.uid,
      		cred.gid,
      		addr.family,
      		addr.addr,
		proto,
      		addr.port
      	)      		
end

-- *********************************************************************

function log_failure(point,remote,cred,addr,proto,err)
  local remote = remote or "(unknown)"
  local cred   = cred   or { uid = '(unk)' , gid = '(unk)' , pid = 0 }
  local addr   = addr   or { family = '(unk)' , addr = '(unk)' , port = '(unk)'}
  local proto  = proto  or 0

  syslog('err',"failure: at=%q err=%q rem=%s uid=%s gid=%s family=%s addr=%s proto=%s port=%s",
		point,
  		errno[err],
  		tostring(remote),
      		cred.uid,
      		cred.gid,
      		addr.family,
      		addr.addr,
		proto,
      		addr.port
      	)
end

-- *********************************************************************

function main(req)
  local remote
  local cred
  local addr
  local proto
  local sock
  local err
  local _

  local function shutdown(s)
    req:close()
    sig.default(s)
    proc.kill(proc.PIC,s)
    proc.exit(1)
  end

  if sig.caught(sig.INT) then
    shutdown(sig.INT)
  elseif sig.caught(sig.TERM) then
    shutdown(sig.TERM)
  end

  remote,cred,addr,proto,err = req:read()
  
  if err ~= 0 then
    if err ~= errno.EINTR then
      syslog('err',"req:read() = %s",errno[err])
      if remote then req:send_err(remote,err) end
    end
    return main(req)
  end
  
  if request_okay(cred,addr,proto) then
    sock,err = net.socket(addr.family,proto)
    if err ~= 0 then
      log_failure('socket',remote,cred,addr,proto,err)
      req:send_err(remote,err)
      return main(req)
    end
    
    sock.reuseaddr = true
    
    err = sock:bind(addr)
    if err == 0 then
      log_success(remote,cred,addr,proto)
      req:send_fd(remote,sock:fd())
    else
      log_failure('bind',remote,cred,addr,proto,err)
      req:send_err(remote,err)
    end
    
    sock:close()
  else
    log_failure('request_okay',remote,cred,addr,proto,errno.EPERM)
    req:send_err(remote,errno.EPERM)
  end
  
  return main(req)
end

-- *********************************************************************

if not pcall(dofile,"/home/spc/source/daemon/acl/version.lua") then
  VERSION = 0
end

syslog.open('ipacld','daemon')
syslog('notice',"ipacld " .. VERSION .. " starting up")

if arg[1] == nil then
  dofile("ipacl.lua")
else
  dofile(arg[1])
end

sig.catch(sig.INT)
sig.catch(sig.TERM)

local sock,err = ipacl_s.open()
if err ~= 0 then
  syslog('err',"ipacl_s.open() = %s",errno[err])
  os.exit(1)
end

main(sock)
